### ISSUE TITLE
Upload modified LNO profile

### ISSUE THREAD

**Issue by zxdawn** [behr-github/Lightning-AMF-Effects#1]
Hi Josh,

What about the bimodal profile of LNO emission from Ott et al. (2010)? Could you upload modified module_lightning_nox_ott.F?

Thank you,
Xin

**Comment by behr-github** [comment]
Those changes are available in our modified WRF-Chem repository:

https://github.com/CohenBerkeleyLab/WRF-Chem-R2SMH/commit/eea91c0fa7e5196255f0d5466ee8bc4b31d4c289

I would also encourage you to do some research into how representative those profiles are for your domain, as the Ott profiles are based on 3 US and 1 European measurement campaign.
