### ISSUE TITLE
Upper boundary condition

### ISSUE THREAD

**Issue by zxdawn** [behr-github/Lightning-AMF-Effects#2]
https://github.com/behr-github/Lightning-AMF-Effects/blob/5891bdf696e6b319a6ecafd12f48671e9d3d3e44/WRF-Namelists/namelist.input.nudge#L164

~~Since you're using upper boundary condition, you need to specify the name of file according to the User's Guide:~~

> To use the upper boundary conditions, the user is required to provide two additional
> input data files:
> - the file clim_p_trop.nc that includes a climatology for tropopause levels
> - an input file with upper boundary conditions for gas species. The filename for the boundary conditions is provided to the WRF model via the chemistry namelist variable “fixed_ubc_inname”.

**Comment by zxdawn** [comment]
Sorry, I made a mistake ...
It's `have_bcs_upper = “.true.”`.
By the way, maybe it's better to use upper boundary condition especially long simulation.

**Comment by zxdawn** [comment]
If you use this option, you can modify the part of `registry.chem` to get the tropopause directly:

https://github.com/CohenBerkeleyLab/WRF-Chem-R2SMH/blob/52309055b848a5503f96d2adb84ba9c99feb31ec/Registry/registry.chem#L420-L423

If you don't want to set the upper boundary condition, you can just use the module of tropopause.

That will simplify the calculation of tropopause in `WRF_Util`: https://github.com/CohenBerkeleyLab/WRF_Utils/issues/3

**Comment by joshua-laughner** [comment]
We are investigating the effect of including an upper boundary condition. This repo is not under active development; it is an archive to support www.atmos-meas-tech.net/10/4403/2017/. No further changes will be made.
